Repository NTI-Gymnasieingenjor/RedCrossAction-Atlantic, pull requests merged in 2020-10, with the labels that each got.

#14 Fix area input prompts if empty
  public/js/script.js
  views/pages/dashboard.pug
  views/pages/signup.pug
Labels: enhancement

#15 Fix sent from volunteer confusing
  views/pages/dashboard.pug
Labels: enhancement, hacktoberfest-accepted

#16 Comments and smmall fixes
  public/js/script.js
  src/app.js
  src/routes/api.js
  src/routes/jour.js
  src/routes/volunteer.js
  views/partials/navbar.pug
Labels: enhancement, hacktoberfest-accepted

#17 Fix sms-draft following sms-text input
  public/css/style.css
  public/js/script.js
Labels: enhancement, hacktoberfest-accepted

#18 Fix sms-draft jumping around
  public/js/script.js
Labels: bug, hacktoberfest-accepted

#22 add map
  views/volunteer/dashboard.pug
Labels: enhancement, hacktoberfest-accepted

#23 Tests
  public/js/script.js
  src/routes/api.js
  src/routes/volunteer.js
  tests/test_api.py
  tests/test_homepage.py
  tests/test_jour_login.py
  tests/test_send_sms.py
  tests/test_signup.py
  tests/test_volunteers.py
  views/pages/signup.pug
  views/volunteer/confirm.pug
  views/volunteer/signup_complete.pug
Labels: enhancement, hacktoberfest-accepted
